<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Game</RootNamespace>
    <AssemblyName>RetroArcade</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RetroArcade.Tests\**\*.cs" />
    <EmbeddedResource Remove="RetroArcade.Tests\**\*" />
    <None Remove="RetroArcade.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="gameconfig.json.example" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RetroArcade.Tests" />
  </ItemGroup>
</Project>
